# -*- coding: utf-8 -*-
"""FineTuning-Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1GaYC8Su9Iqb4VLqny71UiVzwRwd9Zc

### **Check GPU**
"""

import torch

if torch.cuda.is_available():
    print("GPU available: True")
    print("GPU name:", torch.cuda.get_device_name(0))
    print("VRAM:", round(
        torch.cuda.get_device_properties(0).total_memory / 1e9, 1
    ), "GB")
else:
    print("GPU not enabled.")

"""### **Install Unsloth**"""

!pip install unsloth -q
print("Installation complete")

"""### **Imports**"""

from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig
from datasets import Dataset
import json
import torch

print("All imports done")

"""### **Load and Verify Dataset**"""

# Load your healthcare dataset from uploaded file
with open("healthcare_data.json", "r") as f:
    raw_data = json.load(f)

print(f"Total examples loaded: {len(raw_data)}")
print(f"\nFirst example:")
print(f"Instruction: {raw_data[0]['instruction']}")
print(f"Output: {raw_data[0]['output'][:100]}...")
print(f"\nLast example:")
print(f"Instruction: {raw_data[-1]['instruction']}")

"""### **Format Dataset**"""

def format_example(example):

    # Build text in Qwen chat format
    text = (
        "<|im_start|>system\n"
        "You are a professional healthcare assistant. "
        "Provide accurate, clear, and helpful medical information. "
        "Always recommend consulting a doctor for personal medical advice."
        "<|im_end|>\n"
        "<|im_start|>user\n"
        f"{example['instruction']}<|im_end|>\n"
        "<|im_start|>assistant\n"
        f"{example['output']}<|im_end|>"
    )

    return {"text": text}

# Convert to HuggingFace Dataset
hf_dataset = Dataset.from_list(raw_data)

# Apply formatting
dataset = hf_dataset.map(
    format_example,
    remove_columns=hf_dataset.column_names
)

# Split 90% train 10% test
split      = dataset.train_test_split(test_size=0.1, seed=42)
train_data = split["train"]
test_data  = split["test"]

print(f"Train examples: {len(train_data)}")
print(f"Test examples:  {len(test_data)}")
print(f"\nFormatted sample:")
print(train_data[0]["text"][:400])

"""### **Load Qwen Model in 4-bit (QLoRA)**"""

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_NAME,
    max_seq_length = 1024,
    load_in_4bit = True,     # QLoRA — 4-bit base model
    dtype = None,
)

print(f"Model loaded: {MODEL_NAME}")
print(f"Parameters: {model.num_parameters():,}")

vram = torch.cuda.memory_allocated() / 1e9
print(f"VRAM used after loading: {vram:.2f} GB")

"""### **Add DoRA Adapters**"""

# Using DoRA — best quality adapter method
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,              # rank — higher than 135M because 0.5B is bigger
    lora_alpha = 32,     # 2 × r
    lora_dropout = 0.05,
    target_modules = [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ],
    use_dora = True,     # DoRA — best quality
    random_state = 42,
)

model.print_trainable_parameters()

"""### **Check VRAM Before Training**"""

vram_total = torch.cuda.get_device_properties(0).total_memory / 1e9
vram_used  = torch.cuda.memory_allocated() / 1e9
vram_free  = vram_total - vram_used

print(f"Total VRAM:  {vram_total:.1f} GB")
print(f"Used VRAM:   {vram_used:.2f} GB")
print(f"Free VRAM:   {vram_free:.2f} GB")

if vram_free > 5:
    print("VRAM status: Good to train")
elif vram_free > 2:
    print("VRAM status: Tight — reduce batch size if error")
else:
    print("VRAM status: Low — restart runtime")

"""### **Train**"""

trainer = SFTTrainer(
    model = model,
    train_dataset = train_data,
    eval_dataset = test_data,
    args = SFTConfig(
        output_dir = "./qwen-healthcare-dora",

        # Training
        num_train_epochs = 3,
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,

        # Learning rate
        learning_rate = 2e-4,
        warmup_steps = 10,           # ← fixed deprecation warning too
        lr_scheduler_type = "cosine",

        # Logging
        logging_steps = 10,
        eval_strategy = "steps",
        eval_steps = 50,
        save_steps = 100,
        save_total_limit = 2,

        # Precision — fp16 for T4 GPU
        fp16 = True,                 # ← changed from bf16 to fp16
        bf16 = False,                # ← explicitly off

        # Other
        report_to = "none",
        seed = 42,
    ),
)

print("=" * 50)
print("TRAINING: Qwen2.5-0.5B Healthcare Assistant")
print("Adapter:  DoRA")
print("Data:     500 healthcare examples")
print("Epochs:   3")
print("=" * 50)
print()

trainer.train()

print()
print("=" * 50)
print("TRAINING COMPLETE")
print("=" * 50)

"""### **Test Healthcare Model**"""

FastLanguageModel.for_inference(model)

# Healthcare specific test prompts
test_prompts = [
    "What are the early symptoms of diabetes?",
    "What should I do if someone is having a heart attack?",
    "What are common side effects of ibuprofen?",
    "How many hours of sleep does an adult need?",
    "What are signs of depression I should watch for?",
]

print("=" * 55)
print("HEALTHCARE ASSISTANT — MODEL OUTPUT")
print("=" * 55)

for prompt in test_prompts:

    messages = [
        {
            "role": "system",
            "content": (
                "You are a professional healthcare assistant. "
                "Provide accurate, clear, and helpful medical information. "
                "Always recommend consulting a doctor for personal advice."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize = True,
        add_generation_prompt = True,
        return_tensors = "pt"
    ).to("cuda")

    outputs = model.generate(
        input_ids = inputs,
        max_new_tokens = 200,
        temperature = 0.3,
        do_sample = True,
    )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer   = response.split("assistant")[-1].strip()

    print(f"\nQ: {prompt}")
    print(f"A: {answer}")
    print("-" * 55)

"""### **Before vs After Comparison**"""

# Load base model to compare
base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name = "Qwen/Qwen2.5-0.5B-Instruct",
    max_seq_length = 1024,
    load_in_4bit = True,
    dtype = None,
)
FastLanguageModel.for_inference(base_model)

test_prompt = "What are the early warning signs of diabetes?"

messages = [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": test_prompt
    }
]

# Base model response
base_inputs = base_tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

base_outputs = base_model.generate(
    input_ids = base_inputs,
    max_new_tokens = 150,
    temperature = 0.3,
    do_sample = True,
)

base_response = base_tokenizer.decode(
    base_outputs[0],
    skip_special_tokens=True
).split("assistant")[-1].strip()

# Fine-tuned model response
ft_inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

ft_outputs = model.generate(
    input_ids = ft_inputs,
    max_new_tokens = 150,
    temperature = 0.3,
    do_sample = True,
)

ft_response = tokenizer.decode(
    ft_outputs[0],
    skip_special_tokens=True
).split("assistant")[-1].strip()

print("=" * 55)
print("BEFORE vs AFTER FINE-TUNING")
print("=" * 55)
print(f"\nQUESTION: {test_prompt}")
print()
print("BASE MODEL (before):")
print("-" * 30)
print(base_response)
print()
print("FINE-TUNED MODEL (after):")
print("-" * 30)
print(ft_response)


# Free base model from memory
del base_model
torch.cuda.empty_cache()

"""### **Push to Hugging Face Hub**"""

# You need a Hugging Face account and token
# Get token from: https://huggingface.co/settings/tokens
# Create token with WRITE permission

HF_TOKEN    = ""          # paste your token
HF_USERNAME = ""       # your HF username
MODEL_REPO  = "healthcare-qwen2.5-0.5B-dora"

from huggingface_hub import login
login(token=HF_TOKEN)

# Push adapter to Hub
model.push_to_hub(
    f"{HF_USERNAME}/{MODEL_REPO}",
    token = HF_TOKEN
)

tokenizer.push_to_hub(
    f"{HF_USERNAME}/{MODEL_REPO}",
    token = HF_TOKEN
)

print(f"Model pushed to:")
print(f"https://huggingface.co/{HF_USERNAME}/{MODEL_REPO}")
print()
print("Copy this link for your LinkedIn post and GitHub README")